import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6b1f00",
        "surface-container-low": "#f3f4f5",
        "inverse-on-surface": "#f0f1f2",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a4d393",
        "surface-bright": "#f8f9fa",
        "primary": "#303e51",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#022100",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#28501e",
        "on-primary-fixed": "#0d1c2e",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#822800",
        "on-surface-variant": "#44474c",
        "surface-variant": "#e1e3e4",
        "secondary": "#a43c12",
        "on-secondary-fixed": "#380c00",
        "outline-variant": "#c4c6cd",
        "on-primary-container": "#bbcae1",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed-dim": "#ffb59c",
        "primary-container": "#475569",
        "surface-container": "#edeeef",
        "on-tertiary-container": "#a7d695",
        "primary-fixed": "#d5e3fc",
        "surface-container-lowest": "#ffffff",
        "outline": "#75777d",
        "tertiary": "#1e4615",
        "tertiary-container": "#355e2a",
        "primary-fixed-dim": "#b9c7df",
        "surface-tint": "#515f74",
        "on-primary-fixed-variant": "#3a485b",
        "secondary-fixed": "#ffdbcf",
        "secondary-container": "#fe7e4f",
        "inverse-primary": "#b9c7df",
        "tertiary-fixed": "#c0f0ad",
        "background": "#f8f9fa"
      },
      fontFamily: {
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}

export default config
